M48
; DRILL file {KiCad 9.0.3} date 2025-07-16T19:29:39+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-16T19:29:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C7.200
%
G90
G05
T1
X151.91Y-68.115
X157.69Y-68.115
T2
X161.349Y-87.96
X162.365Y-93.04
X163.381Y-87.96
T3
X139.753Y-108.076
M30
